name: Build PlayStation Now List

on:
  push:
  pull_request:
  schedule:
      - cron: '30 9,19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install asciidoctor
      run: sudo apt-get install asciidoctor

    - name: Install pup
      uses: actions/setup-go@v2
      run: go get github.com/ericchiang/pup

    - name: Fetch PSNow Games and Convert
      run: make html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
